[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rate_limit"
authors = [{name = "Ivan Yakob", email = "lifestep95@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/allkotraz/django-rate-limit"
