# Generated by Django 3.2.6 on 2022-06-06 10:52

from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate_limit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
